# Changes here will be overwritten by Copier
_commit: acb4a69
_src_path: git@github.com:python-project-templates/base.git
add_extension: python
email: 3105306+timkpaine@users.noreply.github.com
github: airflow-laminar
project_description: Airflow utilities for configuration of many DAGs and DAG environments
project_name: airflow config
python_version_primary: '3.9'
team: the airflow-config authors
